PROVIDER = "google_docs"
CONNECTOR = "google_docs"

CONTEXT_MODE_SELECTION = "SELECTION"
CONTEXT_MODE_ACTIVE_RESOURCE = "ACTIVE_RESOURCE"
CONTEXT_MODES = (CONTEXT_MODE_SELECTION, CONTEXT_MODE_ACTIVE_RESOURCE)

MUTATION_TYPE_REPLACE_TEXT = "REPLACE_TEXT"
MUTATION_TYPE_INSERT_TEXT = "INSERT_TEXT"
MUTATION_TYPES = (MUTATION_TYPE_REPLACE_TEXT, MUTATION_TYPE_INSERT_TEXT)

TRUST_LEVEL_CONNECTOR_VERIFIED = "connector_verified"
SOURCE_TYPE_CONNECTOR_SELECTION = "connector_selection"
SOURCE_TYPE_CONNECTOR_RESOURCE_EXCERPT = "connector_resource_excerpt"

DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 100
DEFAULT_CONTEXT_TTL_SECONDS = 15 * 60
MAX_ACTIVE_RESOURCE_BYTES = 64 * 1024
DEFAULT_OPERATION_TIMEOUT_SECONDS = 10.0
DEFAULT_READ_RETRY_LIMIT = 1
